name: Setup Kustomoze
description: |
  Install Kustomize
inputs:
  version:
    required: true
    default: 4.5.5
    description: The Kustomize version to install

runs:
  using: composite
  steps:
    - shell: bash
      name: Install
      run: ${{ github.action_path }}/setup.sh "${{ inputs.version }}"
