name: Test Action

on:
  push:
    branches:
      - "**"

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3


      - name: Setup Kustomize
        uses: ./
        with:
          version: 4.0.2

      - run: kustomize version

      - name: Setup Kustomize
        uses: ./

      - run: kustomize version
